[build]
  # Define o diretório base onde o pnpm install e o build command serão executados
  base = "client"
  # Define o comando de build
  command = "pnpm install && pnpm run build"
  # Define o diretório de publicação (relativo ao Base directory)
  publish = "client/dist"

# Configuração para o roteamento SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200