[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist/public"
  base = "."

# Configuração para o roteamento SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração de Node.js
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

# FORÇA A VARIÁVEL DE AMBIENTE NO BUILD DE PRODUÇÃO
[context.production.environment]
  VITE_API_URL = "https://detector-smishing-backend.onrender.com"
