# Configuração do Netlify para o Detector de Smishing
# Este arquivo deve estar na raiz do repositório

[build]
  # Comando para fazer build do frontend
  command = "pnpm install && pnpm run build"
  
  # Diretório que será publicado (resultado do build do Vite)
  publish = "dist/public"
  
  # Diretório base do projeto
  base = "."

# Configuração para o roteamento SPA (Single Page Application)
# Redireciona todas as rotas para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança e CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuração de Node.js
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
