services:
  - type: web
    name: detector-smishing-backend
    runtime: python
    plan: free
    region: oregon
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
